version: "3.0"

services:
  myredis:
    image: redis

  myvotingapp: 
    image: votingapp
    build:
      dockerfile: Dockerfile
      context: ./src/votingapp
    ports:
      - 8080:80
    environment:
      REDIS: "myredis:6379"
  
  mytest:  
    image: votingapp-test
    build:
      context:
        ./votingapp-test
    environment: 
      VOTINGAPP_HOST: "myvotingapp"
  