apiVersion: v1
kind: Namespace
metadata:
  name: votingapp

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myvotingapp
  name: myvotingapp
  namespace: votingapp
spec:
  containers:
  - image: lasalleeriktordera/votingapp
    name: votingapp    
    env: 
      - name: REDIS
        value: "myredis:6379"

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myredis
  name: myredis
  namespace: votingapp
spec:
  containers:
  - image: redis
    name: myredis

---

apiVersion: v1
kind: Service
metadata:
  name: myvotingapp
  namespace: votingapp
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: myvotingapp

---

apiVersion: v1
kind: Service
metadata:
  name: myredis
  namespace: votingapp
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: myredis

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myvotingapp
  name: myvotingapp
  namespace: votingapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myvotingapp
  template:
    metadata:
      labels:
        app: myvotingapp
    spec:
      containers:
      - name: myvotingapp
        image: lasalleeriktordera/votingapp
        env: 
        - name: VOTINGAPP_HOST
          value:  "myvotingapp"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myredis
  name: myredis
  namespace: votingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myredis
  template:
    metadata:
      labels:
        app: myredis
    spec:
      containers:
      - name: myredis
        image: redis
---

apiVersion: v1
data:
  nginx.conf: |-
    events { worker_connections 1024; }

    http {
        include /etc/nginx/mime.types;

        upstream voting{
            server myvotingapp;
        }

        server {
            listen 80;

            location / {
                proxy_pass         http://voting/;
                proxy_redirect     off;
                proxy_set_header   Host $host;
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Host $server_name;
            }

            location /ws {
                proxy_pass http://voting/ws;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
            }
        }

    }
kind: ConfigMap
metadata:
  name: mynginxconfig
  namespace: votingapp

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mynginx
  name: mynginx
  namespace: votingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: mynginx
        image: nginx

---

apiVersion: v1
kind: Service
metadata:
  name: mynginx
  namespace: votingapp
spec:
  ports:
  - nodePort: 32488
    port: 80
    targetPort: 80
  selector:
    app: mynginx
  type: NodePort