apiVersion: v1
kind: Namespace
metadata:
  name: votingapp

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myvotingapp
  name: myvotingapp
  namespace: votingapp
spec:
  containers:
  - image: lasalleeriktordera/votingapp
    name: votingapp    
    env: 
      - name: REDIS
        value: "myredis:6379"

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myredis
  name: myredis
  namespace: votingapp
spec:
  containers:
  - image: redis
    name: myredis

---

apiVersion: v1
kind: Service
metadata:
  name: myvotingapp
  namespace: votingapp
spec:
  ports:
  - nodePort: 32486
    port: 80
    targetPort: 80
  selector:
    app: myvotingapp
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: myredis
  namespace: votingapp
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: myredis
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myvotingapp
  name: myvotingapp
  namespace: votingapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myvotingapp
  template:
    metadata:
      labels:
        app: myvotingapp
    spec:
      containers:
      - name: myvotingapp
        image: lasalleeriktordera/votingapp
        env: 
        - name: VOTINGAPP_HOST
          value:  "myvotingapp"

